name: Automation

on:
  workflow_dispatch:
  schedule:
  - cron: "0 * * * *"

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          git clone https://github.com/anantkaul/LethalWeapon.git old
          git clone https://github.com/vmwaresecurity/LethalWeapon.git new
          pwd
          diff -r old new > /opt/diff.txt
          set -x

      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          # Required mail server address:
          server_address: smtp.gmail.com
          # Required mail server port:
          server_port: 465
          # Required mail subject:
          subject: Github Actions job result
          # Required recipients' addresses:
          to: anant.kaul.18cse@bmu.edu.in
          # Required sender full name (address can be skipped):
          from: Luke Skywalker # <user@example.com>
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          # Optional plain body:
          body: Build job of ${{github.repository}} completed successfully!
          # Optional HTML body read from file:
#           html_body: file://README.html
#           # Optional carbon copy recipients:
#           cc: kyloren@example.com,leia@example.com
#           # Optional blind carbon copy recipients:
#           bcc: r2d2@example.com,hansolo@example.com
          # Optional unsigned/invalid certificates allowance:
          ignore_cert: true
          # Optional attachments:
          attachments: file://opt/diff.txt
#           # Optional priority: 'high', 'normal' (default) or 'low'
#           priority: low
